version: "3.1"

services:

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./php/services:/srv/www/services
      - ./static:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - nodejs

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'lamoda'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
      - .:/db/dump/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '80:80'
    environment:
      MYSQL_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'password'

  nodejs:
    build: ./nodejs
    environment:
      NODE_ENV: production
    working_dir: /home/app
    restart: always
    volumes:
      - ./nodejs:/home/app
    depends_on:
      - php
    command: npm start
    links:
      - redis

  php:
    build: /php
    links:
      - db
    volumes:
      - .:/var/www/html

  redis:
    image: redis:alpine
    volumes:
      - /var/redis/data:/data

networks:
  mysql-phpmyadmin:

volumes:
  my-db:
